# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Graebert.AresCommander.2024
PackageVersion: 24.0.1114
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://files.graebert.com/ares/2024.0.1.1114/ARES_C_2024_SP0_24.0.1.1114_1669_x64.exe
  InstallerSha256: D5EF23D8B035E81377A303234CCE83A79C458E6278E9F1936B8A26966B2DC047
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
ManifestType: installer
ManifestVersion: 1.0.0

