# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Graebert.AresCommander.2025
PackageVersion: 25.0.1225
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://files.graebert.com/ares/25.0.1.1225/ARES_C_2025_SP0_25.0.1.1225_3329_x64.exe
  InstallerSha256: F7F97254D38DD1A72B6152AEC225499B7B3FF4A53F04EE4B9F68E40E66597FB1
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
ManifestType: installer
ManifestVersion: 1.0.0

